seed_everything: 1698126222
trainer:
  logger: true
  checkpoint_callback: false
  callbacks: null
  default_root_dir: null
  gradient_clip_val: 0.0
  gradient_clip_algorithm: norm
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: null
  gpus: -1
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 40
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 200
  min_epochs: null
  max_steps: null
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: 100
  log_every_n_steps: 50
  accelerator: null
  sync_batchnorm: false
  precision: 32
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 0
  truncated_bptt_steps: null
  resume_from_checkpoint: null
  profiler: null
  benchmark: true
  deterministic: true
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: false
  terminate_on_nan: false
  auto_scale_batch_size: false
  prepare_data_per_node: true
  plugins: null
  amp_backend: native
  amp_level: O2
  distributed_backend: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
model:
  base_lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  fc_bias: true
  lr_factor: 0.1
  milestones:
  - 80
  - 120
  finetuning_epochs: 0
  finetuning_lr: 0.005
  lambda_ce: 0.5
  lambda_hkd: 0.01
  lambda_sp: 0.01
  lambda_ft: 0.2 # 1
  lambda_weq: 0.001
  num_inv_iters: 5000
  inv_lr: 0.001
  inv_tau: 1000.0
  inv_alpha_pr: 0.001
  inv_alpha_rf: 50.0
  inv_resume_from: null
data:
  root: /data/shared/
  dataset: cifar100
  batch_size: 128
  num_workers: 4
  val_splits: 0
  val_seed: 42
  num_tasks: 5
  current_task: 0
  class_order: [23, 8, 11, 7, 48, 13, 1, 91, 94, 54, 16, 63, 52, 41, 80, 2, 47, 87, 78, 66, 19, 6, 24, 10, 59, 30, 22, 29, 83, 37, 93, 81, 43, 99, 86, 28, 34, 88, 44, 14, 84, 70, 4, 20, 15, 21, 31, 76, 57, 67, 73, 50, 69, 25, 98, 46, 96, 0, 72, 35, 58, 92, 3, 95, 56, 90, 26, 40, 55, 89, 75, 71, 60, 42, 9, 82, 39, 18, 77, 68, 32, 79, 12, 85, 36, 17, 64, 27, 74, 45, 61, 38, 51, 62, 65, 33, 5, 53, 97, 49]
  init_task_splits: 0
  task_seed: 42
  test_mode: seen
  memory_algo: herding
  memory_size: 0
  dynamic_memory: false
